### ISSUE TITLE
Cannot create database

### ISSUE THREAD

**Issue by he-sk** [c3subtitles/L2S2#104]
`npm run database` fails with the following output:

```
cartman:l2s2 test$ npm run database

> l2s2@0.0.1 database /Users/test/l2s2
> nf run node server/dist/init/createDatabase.js

[OKAY] Loaded ENV .env File as KEY=VALUE Format
/Users/test/l2s2/server/dist/init/createDatabase.js:5
var _bcryptjs2 = babelHelpers.interopRequireDefault(_bcryptjs);
                 ^

ReferenceError: babelHelpers is not defined
    at Object.<anonymous> (/Users/test/l2s2/server/dist/init/createDatabase.js:5:18)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by MTRNord** [comment]
+1 I have the same error

**Comment by Ryuno-Ki** [comment]
Looks like `babelHelpers.js` not being created, but referenced.

**Comment by marudor** [comment]
File is never created. It should be referenced though. (File exists in root)
Just import it. Will fix soon.
